### ISSUE TITLE
How to load it with webpack encore

### ISSUE THREAD

**Issue by iatanasov77** [CoderLine/alphaTabWebsite#14]
# Question 

* Version used: v0.9.1.145
* Platform used: JavaScript

I try to use this library with webpack-encore. I import it:

`
import '../../vendor/AlphaTab/AlphaTab.js';
...
` 

When i load the page in the browser i recieve an error: Uncaught ReferenceError: window is not defined

I have not this problem when i use it normal:
`<script type="text/javascript" src="/assets/AlphaTab/AlphaTab.js"></script>
`

**Comment by Danielku15** [comment]
The website already mentions now some pieces about the bundling: https://www.alphatab.net/docs/getting-started/installation-web#additional-notes

I transferred this issue to the website repo to add some docs on integration with particular bundlers.
