### ISSUE TITLE
Possibility to drag&drop files on index example

### ISSUE THREAD

**Issue by thoun** [CoderLine/alphaTabWebsite#30]
A nice improvement would be to allow website to display custom GP files, to check their loading is fine with current version of alphaTab. It would allow me to know if a loading bug is linked to my project or alphaTab.
By the way, what version is used for the website ? Latest release or the develop branch ?

**Comment by Danielku15** [comment]
Sounds like a good idea. Drag&Drop but maybe also a classical file opener via button in the toolbar. 

Currently the website uses the `develop` version, it links to the `@alpha` tag on NPM via JsDelivr. At some point I would like to have a version selector on the website to switch between the stable and alpha/develop version. 

![image](https://user-images.githubusercontent.com/674916/105213882-8f521f80-5b4f-11eb-9240-833197bed907.png)

**Comment by Danielku15** [comment]
And done 😉 Should go live in a few mins.

**Comment by thoun** [comment]
that was quick ! thanks !
