### ISSUE TITLE
print function execute twice

### ISSUE THREAD

**Issue by WindBise** [CoderLine/alphaTabWebsite#33]
click print button, and print preview window opens two times

**Comment by Danielku15** [comment]
Please follow our rules regarding reporting bugs and opening discussions.

**Comment by Danielku15** [comment]
That's not happening for me on Chrome90+Windows10. What browser and OS are you using?

**Comment by WindBise** [comment]
It shows on Chrome90+Windows10 and Chrome90+macOS catalina.
Reproduce step:
1. open alphatab.net
2. click print button on canon rock
3. choose print to pdf and click confirm button, the pdf will be downloaded to local file system
4. and then another print window will show up
5. you can print to pdf and download the pdf file again

what's more, the tab pdf has no filename, add tab name to pdf will be more convinence for user IMHO.

**Comment by Danielku15** [comment]
Thanks for the additional steps to reproduce. I followed them and could still not see any duplicate print window. Please look at the following recordings, is there something you do different?

**Chrome90-Windows10**
![Chrome90-Windows10](https://user-images.githubusercontent.com/674916/117979701-7dc99900-b333-11eb-9420-460d71148563.gif)
**Chrome90-MacOSCatalina**
![Chrome90-MacOSCatalina](https://user-images.githubusercontent.com/674916/117979710-7efac600-b333-11eb-9ae4-9a4245bb7969.gif)


Regarding the file name I would have to check. Please open a [New Feature Request Discussion](https://github.com/CoderLine/alphaTab/discussions/categories/ideas) over at the main library repo regarding this topic. I think Chrome uses by default the page title as file name, but to provide the right feature some clarifications might be needed there.

**Comment by WindBise** [comment]
![output](https://user-images.githubusercontent.com/34051534/118342833-d37e8b00-b557-11eb-8609-9c51cd198ff2.gif)
Weird...In my environment the issue still shows even in safari. This gif shows operation in chrome 90.0.4430.212 and macOS 10.15.6. I've no idea where's the problem.

**Comment by gallegretti** [comment]
So, I've been able to reproduce this issue when using the development branch for alphaTab, just like @WindBise demonstrated on my Win 10, Chrome 100.0.4896.127. This is what I figured:

* The `window.print` function is called inside the [`alphaTab.renderer.postRenderFinished` trigger.](https://github.com/CoderLine/alphaTab/blob/f96e7b3b97fa1dfb95a14effb932d361e2eae905/src/platform/javascript/AlphaTabApi.ts#L77)

* But this triggers twice, first when the new window opens and the second time when you print or cancel the prompt.

* What I think is happening is alphaTab is really rendering twice, [first by the `print` function,](https://github.com/CoderLine/alphaTab/blob/f96e7b3b97fa1dfb95a14effb932d361e2eae905/src/platform/javascript/AlphaTabApi.ts#L79) and the second time after the print prompt is closed by the [AlphaTabApiBase](https://github.com/CoderLine/alphaTab/blob/develop/src/AlphaTabApiBase.ts#L163-L166),

* Removing the `alphaTab.renderTracks(this.tracks);` from the [`print`](https://github.com/CoderLine/alphaTab/blob/f96e7b3b97fa1dfb95a14effb932d361e2eae905/src/platform/javascript/AlphaTabApi.ts#L79) function seems to solve the issue for me

@Danielku15 Let me know what you think, I'd be happy to create a PR with this fix.

**Comment by Danielku15** [comment]
Thanks for the investigation. In this case it seems like a bug in alphaTab itself, not the website. Filed a bug with the related description here: https://github.com/CoderLine/alphaTab/issues/844
